name: Update Stremio SideStore Source

on:
  schedule:
    - cron: '0 */12 * * *' # Runs automatically every 12 hours
  workflow_dispatch: # Manual Trigger

permissions:
  contents: write

jobs:
  update-source:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Run updater script
      run: python update_source.py

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        
        # Check if the file was created before running git commands
        if [ -f "source.json" ]; then
          git add source.json
          git diff-index --quiet HEAD || git commit -m "Automated update of Stremio source metadata"
          git push
        else
          echo "Error: source.json was not generated by the python script."
          exit 1
        fi
